### ISSUE TITLE
Where does stdout go?

### ISSUE THREAD

**Issue by vcapra1** [flybywiresim/msfs-rs#10]
I build the `log` example and put it in a simple package in the Community folder, and started the sim, but don't see any of the log output in the debug console.  Where does this output go?  Is there a way to write to the debug log in the sim?

**Comment by Gurgel100** [comment]
Is this issue still relevant?

**Comment by MrMinimal** [comment]
@vcapra1 The output is not in the sim console, the log example compiles to a standalone .exe file which you have to run using a terminal/console. The output is then printed in said console.

@Gurgel100 I doubt it is still relevant, just tested it. Compiles and prints sim data just fine.

**Comment by devsnek** [comment]
the log example contains two different demos.
- lib.rs is used with the wasm32-wasi standalone target as a cdylib. when you load this into the sim the output should show up in the ingame developer console.
- main.rs is used if you compile it to an exe. when this is run you'll see the output in a normal console window.
