### ISSUE TITLE
event_id_counter not incremented when calling subscribe_to_system_event()

### ISSUE THREAD

**Issue by juliansebline** [flybywiresim/msfs-rs#19]
The event_id counter is not incremented when calling `subscribe_to_system_event()` whereas it is when calling `map_client_event_to_sim_event()`.

This leads to system events not being handled.

Use case;

I'm calling first `subscribe_to_system_event` with 0 as `event_id` then the different aspects call `map_client_event_to_sim_event`. My event with id 0 gets overwritten and therefore is not caught.

Suggestion: `subscribe_to_system_event` should use `event_id_counter` and return the id as well.

**Comment by beheh** [comment]
Glancing at the code, the event_id is a parameter to `subscribe_to_system_event`. It's unclear to me how a caller should choose this. However, `event_id_counter` is not involved here, so why should this function increment it?

If the `event_id` were chosen by `subscribe_to_system_event` I see how this would make sense, but as it's currently injected I'm not sure that makes sense.

**Comment by juliansebline** [comment]
> If the `event_id` were chosen by `subscribe_to_system_event` I see how this would make sense, but as it's currently injected I'm not sure that makes sense.

This is exactly what I meant. More context with my current use case in the description.

**Comment by Gurgel100** [comment]
Fixed by #20
