### ISSUE TITLE
WASM error when building log example

### ISSUE THREAD

**Issue by jrvirtue** [flybywiresim/msfs-rs#23]
Using: 
LLVM 17 (also tried 16,15,14)
Rust 1.74.1
git clone https://github.com/flybywiresim/msfs-rs.git
build command: cargo build --target wasm32-wasi
Simple MSFS project with a one COPY asset: copies wasm into modules\

Building and loading the projects generates the following WASM error:

WASM: inNative: ERR_FATAL_UNKNOWN_INSTRUCTION: found 192-0
WASM: ERR_FATAL_UNKNOWN_INSTRUCTION (-249 / ffffff07 )
WASM: Error -249 / ffffff07

**Comment by nonenty** [comment]
use wasm-opt after build. see https://github.com/flybywiresim/aircraft/blob/7b8a0560451e02a1265ebf19d13b18635270be52/package.json#L53C96-L53C148
