### ISSUE TITLE
N duplicated events after N app restarts

### ISSUE THREAD

**Issue by diagonalization-lab** [flybywiresim/msfs-rs#7]
Hi,

I am new to SimConnect but an experienced Rust programmer.

I am writing an MSFS add-in that receives joystick inputs via SimConnect. This Rust API does not seem to support input events, so I hacked up a method for it based on other examples (code is below). However, after *n* restarts I get *n* duplicated input events. 

I figured that I am doing cleanup wrong, and perhaps the `SimConnect` drop handler, which calls `SimConnect_Close` is not getting called when I hit Ctrl+C. I actually bound a key that calls `SimConnect_Close` to manually cleanup, but that doesn't appear to be working either. Any suggestions would be appreciated, thanks!

P.S. Here is my hack for receiving input events. I added this function to `sim_connect.rs`:

```rust
 pub fn map_input_event_to_client_event(
        &mut self,
        input_definition: &str,       
    ) -> Result<sys::DWORD> {
        let event_id = self.event_id_counter;
        self.event_id_counter += 1;
        let mask = false;

        const INPUT_GROUP_ID : u32 = 12; // Arbitrary?
        unsafe {
            let input_definition = std::ffi::CString::new(input_definition).unwrap();
            // Arbitrary?
            let custom_event_name = format!("knobs.{}", event_id);
            let private_event_name = std::ffi::CString::new(custom_event_name).unwrap();

            map_err(sys::SimConnect_MapClientEventToSimEvent(
                self.handle,
                event_id,
                private_event_name.as_ptr(),
            ))?;

            map_err(sys::SimConnect_MapInputEventToClientEvent(
                self.handle,
                INPUT_GROUP_ID,
                input_definition.as_ptr(),
                event_id,
                0,
                sys::SIMCONNECT_UNUSED,
                0,
                if mask { 1 } else { 0 }
            ))?;

            map_err(sys::SimConnect_SetInputGroupState(self.handle, INPUT_GROUP_ID, 1))?;

            map_err(sys::SimConnect_AddClientEventToNotificationGroup(
                self.handle,
                INPUT_GROUP_ID,
                event_id,
                if mask { 1 } else { 0 },
            ))?;
        }
        Ok(event_id)
    }
```

**Comment by devsnek** [comment]
I believe this is a bug in simulator itself, not this library.

**Comment by diagonalization-lab** [comment]
Yeah, I figured as much. After some binary search, its the call to `SimConnect_MapInputEventToClientEvent` that cannot be duplicated in a single simulator session, or bad things happen.
